name: run-tests
run-name: Installs project and runs project tests
on: [ push, pull_request ]
jobs:
  run-tests-nix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16, 18 ]
    name: Tests on Ubuntu with Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: pyvista/setup-headless-display-action@v1
      - run: npm install
      - run: npm run compile
      - run: npm run test-coverage

      - name: Copy Coverage To Predictable Location
        run: cp coverage/cobertura-coverage.xml coverage.cobertura.xml

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
  run-tests-win:
    runs-on: windows-latest
    strategy:
      matrix:
        node: [ 16, 18 ]
    name: Tests on Windows with Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: pyvista/setup-headless-display-action@v1    
      - run: npm install
      - run: npm run compile
      - run: npm run test-coverage
